apiVersion: apps/v1
kind: Deployment
metadata:
  name: faizulkarim-nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: faizulkarim-nodeapp
  template:
    metadata:
      labels:
        app: faizulkarim-nodeapp
    spec:
      containers:
        - name: nodeapp
          image: sunnyboysb/node-app:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: faizulkarim-nodeapp
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 3000
      nodePort: 31110
  selector:
    app: faizulkarim-nodeapp
